# Page settings
baseurl = "localhost:1313"
title = "Kineto Acasa"
languageCode = "ro-RO"
theme = "hugo-elate-theme"

enableRobotsTXT = true

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = "Kinetoterapie acasă la tine. Kinetoterapie la domiciliu București. Recuperare prin Kinetoterapie la tine acasă."
  email = "paul.andrei.onac@gmail.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "Kineto Acasă"
    home = "Acasă"
    work = "Work"
    testimonials = "Testimoniale"
    services = "Services"
    about = "Despre"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Kinetoterapie acasă la tine!"
    subtitle = 'Kinetoterapie acasă la tine. Kinetoterapie la domiciliu București. Recuperare la tine acasă.'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonialele pacienților"
    description = "Ce spun pacienții noștri despre Kineto Acasă, dar si despre Kinetoterapie, Recuperare la Domiciliu."

    [[params.testimonials.item]]
      quote = "Sesiunile de kinetoterapie pentru recuperarea după un AVC au fost cu adevărat benefice. Terapeutul meu a demonstrat o înțelegere profundă a nevoilor mele individuale, creând un plan de tratament personalizat. Cu abilitatea sa de a mă motiva și de a mă încuraja constant, am văzut îmbunătățiri semnificative în mobilitate, echilibru și forță musculară."
      person = 'ova'
      img = "florin-drogeanu.png"
      alt = "Florin Drogeanu"

    [[params.testimonials.item]]
      quote = "Buna ziua, după o operație de tumoare pe creier și un accident vascular, tatăl meu in vârsta de 68 ani, a rămas imobilizat la par, cu pareza pe stânga. Noi, familia am considerat ca ar fi bine sa înceapă de urgentă ședințe de kineto…, și așa l-am întâlnit pe Andrei, o persoana excepțională, care îmi tratează părinții cu răbdare și respect. Datorită lui, intr-un timp record,  tatăl meu, poate sta in șezut, și, ajustat de cineva, poate face câțiva pași ( un miracol pentru noi)."
      person = 'Florin Drogeanu'
      img = "costica-grigore.png"
      alt = "Costica Grigore"

    [[params.testimonials.item]]
      quote = "Sesiunile de kinetoterapie nu au fost doar o parte esențială a procesului meu de recuperare, ci și o sursă de inspirație și încredere în propriile capacități. Recomand cu căldură aceste sesiuni pentru toți cei care se recuperează după un AVC. Este o investiție în sănătate și bunăstare care merită fiecare efort depus. ⭐⭐⭐⭐⭐"
      person = 'Sanda Abrasu'
      img = "person2.jpg"
      alt = "Sanda Abrasu"

  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "Despre Andrei"
    description = "Sunt un fizioterapeut cu experiență, care oferă o gamă largă de tratamente axate pe recuperare pentru a le permite pacienților să se restabilească."

    [[params.about.item]]
      name = "Andrei"
      position = "Fiziokinetoterapeut"
      description = "Licențiat în Kinetoterapie și Motricitate Specială (Universitatea “Dunărea de Jos”)"
      img = "person1.jpg"
      alt = "Andrei"
      social = [
        ["icon-facebook", "https://www.facebook.com/paul.andrei.onac"],
        ["icon-linkedin", "https://www.linkedin.com/in/onac-paul-andrei"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Kinetoterapeut experimentat"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Recuperări post AVC"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Recuperări post-traumatice"
      icon = "icon-code"
      from = 0
      to = 150
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Ședințe efectuate"
      icon = "icon-cup"
      from = 0
      to = 2302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Pacienți Mulțumiti"
      icon = "icon-people"
      from = 0
      to = 152
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "București, Sector 3"],
        ["icon-phone", "+40 753 789 020"],
        ["icon-envelope", "paul-andrei-onac@gmail.com"],
        ["icon-globe", '<a href="https://paul-andrei-onac.ro" target="_blank">Kinetoterapeut</a>']
      ]

    name = "Nume"
    email = "Email"
    phone = "Telefon"
    message = "Mesaj"
    button = "Trimite mesaj"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Kineto Acasă 2023. Toate drepturile rezervate.'
    links = [
        ["icon-facebook", "https://www.facebook.com/paul.andrei.onac"],
        ["icon-linkedin", "https://www.linkedin.com/in/onac-paul-andrei"],
        ["icon-globe", "https://paul-andrei-onac.ro" ]
      ]
